# Generated by Django 3.2.8 on 2022-01-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20220103_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='content',
            new_name='review',
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], null=True),
        ),
    ]
