# Generated by Django 3.2.8 on 2022-01-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
