# Generated by Django 3.2.8 on 2021-11-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
